-- Monitor configuration.
--
-- NOT the last word: hyprland.lua ends with a dofile of
-- hyprmoncfg-monitors.lua, which is generated by hyprmoncfg and loads AFTER
-- this file. It sets the same two monitors by `desc:` instead of connector
-- name, so its position/scale win. That is why HDMI-A-1 reports x=1920 here
-- rather than the 1924 below. Keep the two in step, or delete one.
--
-- List connectors with: hyprctl monitors all
--
-- Identify which connector the Denon is on. Decode the EDID first rather
-- than text-searching the raw blob: `grep` is aliased to `rg` in .zshrc and
-- ripgrep skips binary files, while GNU grep reports a match only on stderr.
-- Decoding first behaves the same under grep, rg and ugrep:
--
--   for c in /sys/class/drm/card*-*/; do
--     edid-decode "$c/edid" 2>/dev/null | grep -q DENON-AVR && basename "$c"
--   done
--
-- hyprmon's profile binds (CTRL+SHIFT+F1..F3, see hypr/bindings.lua) are
-- BROKEN on Hyprland 0.56.2. hyprmon applies profiles by shelling out to
-- `hyprctl keyword monitor "<name>,<mode>,<pos>,<scale>"`, and this build
-- rejects that outright:
--
--   $ hyprctl keyword monitor "HDMI-A-1, 3840x2160@60, 1924x-32, 1.50"
--   keyword can't work with non-legacy parsers. Use eval.
--
-- hyprmon does not check hyprctl's output, so it still prints "Profile
-- applied successfully" while changing nothing. The runtime equivalent that
-- does work is:
--
--   hyprctl eval 'return hl.monitor{output="HDMI-A-1", mode="3840x2160@120.00",
--                                   position="1920x-32", scale=1.5}'
--
-- hyprmoncfg (the newer sibling, /usr/sbin/hyprmoncfg) does understand the
-- Lua format -- it is what generates hyprmoncfg-monitors.lua.

hl.env("GDK_SCALE", "1")

-- Catch-all fallback. Must stay FIRST: later rules override it, so any
-- monitor without an explicit rule below still comes up at its preferred
-- mode instead of staying dark.
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1.25 })

-- Dell S2417DG
hl.monitor({ output = "DP-1", mode = "2560x1440@165.00", position = "0x0", scale = 1.33 })

-- Denon AVR-S760H (4K120 via HDMI 2.1 FRL)
hl.monitor({ output = "HDMI-A-1", mode = "3840x2160@120.00", position = "1920x-32", scale = 1.50 })
