# Background and foreground colors
background = #1C3C52
foreground = #3fafef

# Standard colors
palette = 0=#1C3C52
palette = 1=#BD5B3D
palette = 2=#5A6442
palette = 3=#ccbd63
palette = 4=#00397B
palette = 5=#003E82
palette = 6=#0388B4
palette = 7=#3fafef

# Bright colors
palette = 8=#95aebf
palette = 9=#da927c
palette = 10=#8d9d64
palette = 11=#e6dca5
palette = 12=#0064d7
palette = 13=#006ade
palette = 14=#14c5ff
palette = 15=#ffffff
