background            #1C3C52
foreground            #3fafef

# black
color0  #1C3C52
color8  #95aebf

# red
color1  #BD5B3D
color9  #da927c

# green
color2  #5A6442
color10 #8d9d64

# yellow
color3  #ccbd63
color11 #e6dca5

# blue
color4  #00397B
color12 #0064d7

# magenta
color5  #003E82
color13 #006ade

#cyan
color6  #0388B4
color14 #14c5ff

#white
color7  #3fafef
color15 #ffffff


